# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
/api/*  https://api.nasa.gov/:splat  200

[[headers]]
   for = "/.netlify/functions/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
       # These are optional